### ISSUE TITLE
[MCLEAN-86] Unable to delete files because of umlauts

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-clean-plugin#159]
**[Phillip Wirth](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=schaum)** opened **[MCLEAN-86](https://issues.apache.org/jira/browse/MCLEAN-86?redirect=false)** and commented

I am not able to delete some files with mvn clean

The LOCALE vairable is set to `C`

Project properties:

```java
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
 <project.reporting.sourceEncoding>UTF-8</project.reporting.sourceEncoding>
 <file.encoding>utf-8</file.encoding>

```

 

I am able to build the project (same locale setting) and deep inside the target folder I can see why it fails

```java
zarathustra@wotan ..oesung/oms/xxx/xxx/coupons/domain/meta (git)-[master] % ll 
total 24 
-rw-rw-r--. 1 zarathustra zarathustra 1139 Apr 12 16:37 'MetaAdvertisementOutletCity$D'$'\303\274''sseldorfLiteral.class' 
-rw-rw-r--. 1 zarathustra zarathustra 1115 Apr 12 16:37 'MetaAdvertisementOutletCity$K'$'\303\266''lnLiteral.class' 
-rw-rw-r--. 1 zarathustra zarathustra 1127 Apr 12 16:37 'MetaAdvertisementOutletCity$M'$'\303\274''nchenLiteral.class' 
-rw-rw-r--. 1 zarathustra zarathustra 1127 Apr 12 16:37 'MetaAdvertisementOutletCity$M'$'\303\274''nsterLiteral.class' 
-rw-rw-r--. 1 zarathustra zarathustra 1131 Apr 12 16:37 'MetaAdvertisementOutletCity$N'$'\303\274''rnbergLiteral.class' 
-rw-rw-r--. 1 zarathustra zarathustra 1143 Apr 12 16:37 'MetaAdvertisementOutletCity$Saarbr'$'\303\274''ckenLiteral.class'

```

 

Running `mvn -X clean` results in the following error:

```java
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213) 
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154) 
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146) 
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117) 
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81) 
 at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) 
 at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) 
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309) 
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194) 
 at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107) 
 at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993) 
 at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345) 
 at org.apache.maven.cli.MavenCli.main(MavenCli.java:191) 
 at sun.reflect.NativeMethodAxxxssorImpl.invoke0(Native Method) 
 at sun.reflect.NativeMethodAxxxssorImpl.invoke(NativeMethodAxxxssorImpl.java:62) 
 at sun.reflect.DelegatingMethodAxxxssorImpl.invoke(DelegatingMethodAxxxssorImpl.java:43) 
 at java.lang.reflect.Method.invoke(Method.java:498) 
 at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) 
 at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) 
 at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) 
 at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) 
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to clean project: Failed to delete /home/zarathustra/code/oms-xxx-xxx/coupons/coupons-domain/target/classes/com/wunschloesung/oms/xxx/xxx/coupons/domain/meta
 at org.apache.maven.plugins.clean.CleanMojo.execute(CleanMojo.java:212) 
 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) 
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) 
 ... 20 more 
Caused by: java.io.IOException: Failed to delete /home/zarathustra/code/oms-xxx-xxx/coupons/coupons-domain/target/classes/com/wunschloesung/oms/xxx/xxx/coupons/domain/meta 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:251) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:193) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160) 
 at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:118) 
 at org.apache.maven.plugins.clean.CleanMojo.execute(CleanMojo.java:191) 
 ... 22 more

```

---

**Affects:** 3.0.0

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This cannot work. You must set file encoding before the vm is started.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Reasoning provided, no reaction.
