### ISSUE TITLE
[MCLEAN-26] Long pathnames on windows platforms cannot be deleted

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-clean-plugin#214]
**[jd](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=j1234d2003)** opened **[MCLEAN-26](https://issues.apache.org/jira/browse/MCLEAN-26?redirect=false)** and commented

NOTE: Could not find a specific project for file-management and since this project is getting affect by issue in file-management, I am reporting this problem and its solution here.

When projects reside in directory structure that causes absolute pathnames to go beyond 248 (maybe 260 on some Java versions) characters, files cannot be deleted on Windows platform.

On further investigation, the root cause was the org.apache.maven.shared.model.fileset.util.FileSetManager.delete method's failure to successfully delete the class file in projects' target directory.
Caused by: java.io.IOException: Unable to delete file <class-file's very long pathname>
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:433)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:423)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:423)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:423)
at org.apache.maven.shared.model.fileset.util.FileSetManager.delete(FileSetManager.java:189)
at org.apache.maven.plugin.clean.CleanMojo.removeDirectory(CleanMojo.java:185)
... 19 more

This can be fixed by getting a canonical file from the specified file on failure and then attempting a delete as is apparent from the attached patch to file-management dependency's source:

groupId: org.apache.maven.shared
artifactId: file-management
version: 1.0

---

**Affects:** 2.1.1

**Attachments:**
- [MCLEAN-file-management.patch](https://issues.apache.org/jira/secure/attachment/12714817/MCLEAN-file-management.patch) (_726 bytes_)

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

link to PLXUTILS-35

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Applied and bumped to file-management:1.2-SNAPSHOT. Thanks!
