### ISSUE TITLE
[MCLEAN-34] NPE when forcing delete of directory

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-clean-plugin#218]
**[Paul Benedict](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul4christ79)** opened **[MCLEAN-34](https://issues.apache.org/jira/browse/MCLEAN-34?redirect=false)** and commented

I ran "clean site:site" and ended up with this error.

[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.codehaus.plexus.util.FileUtils.cleanDirectory(FileUtils.java:1263)
at org.codehaus.plexus.util.FileUtils.deleteDirectory(FileUtils.java:1224)
at org.codehaus.plexus.util.FileUtils.forceDelete(FileUtils.java:1087)
at org.apache.maven.shared.model.fileset.util.FileSetManager.delete(FileSetManager.java:618)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:594)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:574)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:574)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:574)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:574)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:574)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:574)
at org.apache.maven.shared.model.fileset.util.FileSetManager.removeDir(FileSetManager.java:574)
at org.apache.maven.shared.model.fileset.util.FileSetManager.delete(FileSetManager.java:309)
at org.apache.maven.plugin.clean.CleanMojo.removeDirectory(CleanMojo.java:261)
at org.apache.maven.plugin.clean.CleanMojo.execute(CleanMojo.java:173)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20 seconds
[INFO] Finished at: Mon Jun 30 22:00:11 CDT 2008
[INFO] Final Memory: 4M/9M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.2

**Sub-tasks:**
- [MCLEAN-35](https://issues.apache.org/jira/browse/MCLEAN-35) Upgrade plexus-utils to a new version

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Was already fix in plexus-utils
http://fisheye.codehaus.org/changelog/plexus/?cs=6905

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r692711](http://svn.apache.org/viewvc?view=rev&revision=692711) by updating to plexus-utils:1.5.6.
